docs/tulip_api.md
extmod/amy/Makefile
extmod/amy/README.md
extmod/amy/src/amy.c
extmod/amy/src/amy.h
extmod/amy/src/delay.c
extmod/amy/src/delay.h
extmod/amy/src/envelope.c
extmod/amy/src/oscillators.c
extmod/tulip/modtulip.c
extmod/tulip/py/alles.py
extmod/tulip/tulip.mk
ports/esp32s3/main/CMakeLists.txt

Dan's work here for stereo effects (chorus for now)
We will put this in Tulip now and backport into AMY/Alles once we confirm it works well with the mesh and mono.
Thanks dan!!

Add support for stereo chorus (with a base for more effects to come)

---

extmod/tulip/py/tulip.py

Added screen_size() convenience fuction to tulip.py

---

extmod/tulip/py/tulip.py

A start at tar/untar functionality...

Function in tulip.py to extract .tar files.

---

tools/upip_utarfile.py

- Previous version wrote non-zero size for directories (i.e., whatever value os.stat returned).  Now directories are size 0.
- Previous version would choke on a path that it couldn't os.stat() e.g. a symlink.  Now an OSError on os.stat just means skip the file and continue.

tools/upip_utarfile.py: Tar creation: Fix directory info, skip non-regular files.

---

extmod/amy/src/amy.c
extmod/tulip/py/alles.py

Fixes issue where random pans were being scrambled.

Fix overflow parsing long decimals in alles/amy.

---

extmod/amy/README.md
extmod/amy/src/amy.c

This is to conform to Douglas's expectations, and the convention used in Sound's pan2.

amy: Flip sense of pan so 0=left, 1=right.

---

extmod/amy/src/amy.c
extmod/amy/src/oscillators.c

The int-range, soft-clipped sample values are further shifted down by 1 bit to be in range -16,384..16383 to avoid hard-wrapping on tulip/ESP32 board output.  (may be an issue with i2s bclk polarity, pending investigation).
alles.SAW_UP and SAW_DOWN waves exhibited large low-frequency bumps at their onsets, particularly with fade-in attacks.  This was because the DC offset, which is added to SAW waves to make their integration balance to zero, was constant across each block, while the waveform it was compensating was being linearly amplitude-scaled (when amplitude was varying).  By incorporating the DC offset into the render_lut routine, we can scale it by the linear amplitude ramp at the same time as the underlying looked-up value.  This is much cleaner and gets rid of the low-frequency …

amy: work-around esp32 bit-slip; fix large DC offsets in SAW waves

---

docs/tulip_api.md

Had not been updated after repository tree reorg.

tulip_api.md: Update link to music.py

---

README.md

Testing a normal PR still works after protecting `main`

test commit i want to fail but be ok with a PR

---

docs/music.md
tulip/shared/py/midi.py

This is to support the `synth.release()` instructions in [music.md](https://github.com/shorepine/tulipcc/blob/main/docs/music.md)

Add midi.Synth.release().

---

tulip/shared/memorypcm.c

we have to track dan's changes to pcm in our custom PCM renderer

---

docs/music.md
tulip/shared/py/ui.py

- better woodpiano
- upping amy

better woodpiano docs

---

docs/music.md
tulip/shared/editor.c

- better woodpiano
- upping amy
- fixing esc in editor

fix esc in editor

---

tulip/shared/py/m5_8encoder.py

Copied from: https://github.com/HowManyOliversAreThere/micropython-8encoder 
Device documentation available here: https://docs.m5stack.com/en/unit/8Encoder

Add a simple driver for the M5Stack 8encoder

---

tulip/esp32s3/gt911_touchscreen.c
tulip/esp32s3/pins.h

a fix suggesteed by charlin at makerfabs for the gt911 touchscreen

charlin fix

---

tulip/esp32s3/gt911_touchscreen.c
tulip/esp32s3/main.c

- adding troubleshooting page
- .
- testing 0x14 as well

Testing 0x14 for touchscreen, see #303

---

docs/tulip_api.md
tulip/shared/bresenham.c
tulip/shared/bresenham.h
tulip/shared/modtulip.c

Add an optional width parameter to bg_line. If not given, uses 1.

support line widths in bg_line

---

docs/tulip_api.md
tulip/esp32s3/gt911_touchscreen.c
tulip/fs/ex/calibrate.py
tulip/shared/modtulip.c

Diagnostic tool for more control over CTP positioning. Try this with `world.download('paint.py')` 
(Also, upping AMY)

Setting y-scale for touchscreen, #343

---

tulip/shared/py/midi.py

`SynthOsc` is a simple polysynth controller when each synth voice can be provided by a single osc.  It accepts the arguments for the prototypical osc in its constructor, then initializes a pool of `num_voices` oscs.  It grabs oscs starting from number `first_osc`; it does not currently protect the oscs it uses from being taken by the voices mechanism.
I also fixed the handling of the arpeggiator on midi channel 1 so it will cleanly allow you to replace the synth configured for that channel.
Example:
```
s = midi.SynthOsc(num_voices=6, first_osc=100, wave=amy.PCM, patch=24)  # PCM patch 24 is a pitched steel drum
midi.config.add_synth_object(channel=1, synth_object=s)  # Replace the default channel 1 Juno with the steel drum
```

midi.py: OscSynth now takes kwargs that it will forward to its oscs.

---

docs/tulip_api.md
tulip/esp32s3/multicast.c
tulip/shared/alles.c
tulip/shared/alles.h
tulip/shared/desktop/multicast.c
tulip/shared/modtulip.c
tulip/shared/py/_boot.py
tulip/shared/py/alles.py

- checkpoint for alles on tulip
- new amy
- updating for alles

Ensuring Tulip works with Alles latest

---

tulip/shared/py/midi.py

Douglas Repetto pointed out the existing behavior of ignoring the requested patch for `midi.config.add_synth(channel=10)` was heavy-handed.  Now, Tulip boots to have a `DrumSynth` on midi channel 10, but you can subsequently change it to anything you want.

midi.py: Drums on midi channel 10 can be overridden.

---

tulip/shared/modtulip.c

- just hint the row the tfb_str is on
- upping amy

tfb_str updates row at a time

---

tulip/web/deploy.sh

- changing web deploy to do cache busting js locations
- .
- deploying Tulip Web
- .

cachebuster

---

tulip/shared/py/midi.py

Previously, the "default" synths (6-note Juno patch 0 on MIDI channel 1, PCM-based DrumSynth on MIDI channel 10) were set up via `ensure_midi_config()` which checked to see if the global object `midi.config` had been created, and created it and the default synths if not.  However, the recent addition `midi.config.reset()` releases the default synths while leaving `midi.config` intact, so `ensure_midi_config()` could not be used to recreate the default synths.  
Now we separate the one-time initialization of the `midi.config` structure from the initialization of the default synths, since the latter may need to be repeated after a `midi.config.reset()`.  The `midi.config` structure is instantiated as part of `deferred_midi_config()` (because, I guess, at various times in the past it has …

midi.py: Remove ensure_midi_config, add add_default_synths.

---

tulip/shared/py/arpegg.py
tulip/web/static/examples.js
tulip/web/static/spss.js
www/index.html

- fixing arpegg
- fixing the website

fix up the seq a bit more

---

tulip/shared/py/juno6.py

Previously it was fiddly and likely unsuccessful to simulate selecting a different MIDI channel on the juno6 UI channel selector drop down.
This change adds some hooks to the `JunoDropDown` class, and provides a root-level `juno6.select_midi_channel(1)` that will make the UI act as if the user selected it.

juno6.py: Provide select_midi_channel()

---

tulip/amyboard/amychip.c
tulip/amyboard/main.c
tulip/shared/modtulip.c
tulip/shared/py/amyboard.py
tulip/shared/py/tulip.py

This gets CV in and out working in AMY in amyboard

CV stubs (working) on amyboard

---

tulip/amyboard/amychip.c
tulip/amyboard/pins.h
tulip/shared/py/amyboard.py

- better (but warbly) ADC CV input live in CtrlCoef AMY
- i2c follower working

CV in & i2c follower
