- extmod/amy/src/delay.c
I committed the sin of leaving an outdated comment.  May as well fix it while I'm thinking about it.
> Fix outdated function comment in amy/delay.c.

- extmod/amy/src/amy.c
I think this means it's only been rendering on one core?  Not tested.
> Fix typo ESP_PALATFORM -> ESP_PLATFORM

- extmod/amy/src/amy.c
Replace the atof() used in parsing Amy messages with atoff(), which does the same string -> float conversion, but does not recognize "scientific" format (1.2e7 etc.).  This will allow us to use "e" and "E" as command separators in the Amy wire protocol.  
Note that up until now, it worked to use scientific format in Amy messages, so this is a potentially non-backward-compatible change if anyone is using this format.  There's no real argument for using scientific format in these messages, though.
(I tried to submit this before, not sure what happened.)
> amy.c: atoff() does not consume 'e'/'E' in messages.

- docs/tulip_api.md
The local version of AMY includes features not present in the upstream one.  Make sure users can find the full AMY API documentation from the Tulip repo.
> Link local amy/readme.md to tulip_api.md

- docs/tulip_api.md
Was a link to tulipcc's forked version.  Now that version no longer exists, and the main Amy repo has been brought in-sync.
> tulip_api.md: Update link to AMY Readme.

- docs/tulip_desktop.md
Apparently the MacOS App is now called "Tulip Desktop" not "Tulip CC".
> tulip_desktop.md: Fix path to MacOS binary

- tulip/shared/midi.c
- tulip/shared/midi.h
- tulip/shared/modtulip.c
Before this change, any MIDI message was copied into the `last_midi` buffer, and triggers a request to MicroPython to schedule a run of the MIDI callback routine, which then reads back the content of `last_midi` buffer via `tulip.midi_in()`. When generating MIDI events from a USB keyboard, it was easy to overwrite `last_midi` before the MIDI callback had fetched its results, leading to frequent dropped notes when playing chords.
This change adds an 8-entry FIFO between `callback_midi_message_received()` and `tulip.midi_in()`.  Now, you have to press a whole fist of notes down at approximately the same time to overflow the FIFO.
> midi.c: Add a small FIFO for tulp.midi_in().

- tulip/esp32s3/usb_keyboard.c
- tulip/esp32s3/usb_keyboard.h
This PR adds proper teardown for the USB Host when a QWERTY keyboard or MIDI keyboard is disconnected.  This makes the USB Host interface ready for another device to be connected. 
Before this change, either a QWERTY keyboard or a MIDI keyboard could be connected to the Tulip USB A socket, but once disconnected, the interface would not recognize any subsequent device connection.
After this change, the user can plug and unplug MIDI and QWERTY keyboards at will.  In particular, they can use a QWERTY keyboard to enter commands to launch software expecting MIDI input, then unplug the QWERTY keyboard, plug in a USB-MIDI keyboard, and play away.
In addition, this PR cleans up some of the diagnostic printouts that occur when DEBUG_USB define is set.
> esp32s3/usb_keyboard.c: Support hot-swapping QWERTY<>MIDI.

- tulip/macos/virtualmidi.m
- tulip/shared/midi.c
- tulip/shared/midi.h
This change at least allows it to compile Tulip Desktop on the Mac again.
I can't test it, but I expect it's OK.
> macos/virtualmidi: Bring MacOS MIDI in in-sync with esp32 FIFO changes.

- tulip/esp32s3/touchscreen.c
Similar previous fix, but instead of periodically checking whether last touch was a TOUCH_EVT_PRESS, it checks whether a TOUCH_EVT_PRESS has been received since last forcibly sending a release event to MP.
> Alternative fix for missing touch release

- tulip/tdeck/README.md
- tulip/tdeck/tdeck_keyboard.c
As mentioned in the discussion thread https://github.com/bwhitman/tulipcc/discussions/146#discussioncomment-7738780 here is a PR which provides extra characters to the T-Deck keyboard.
I listen for `alt+c` which the keyboard firmware provides as a formfeed character, this is used to enable an alternate character mode using a bool. On the next key press if the key pressed has an alternative character configured within the `CharMappings` struct it will return the alternative character otherwise it will return the original character, then it will reset the bools state to false to mimic the `sym` key behaviour.
The following extra characters are currently implemented:
| Default | Alternate | Notes |
|---|---|---|
| `q` | `~` |  |
| `w` | `%` |  |
| `e` | `\|` |  |
| `r` | `%` |  |
| `t` | `{` …
> T-Deck: Extra Keyboard Characters

- tulip/esp32s3/esp32_common.cmake
- tulip/esp32s3/main.c
- tulip/esp32s3/tasks.h
- tulip/shared/alles.c
- tulip/shared/alles.h
- tulip/tdeck/main.c
- tulip/tlong/main.c
> Fix for #156

- docs/tulip_desktop.md
- tulip/linux/Makefile
I'm on Arch and I'm trying to get the build for Tulip Desktop working. It looks like the recent change to fork lvgl hasn't been accounted for in the linux Makefiles, so that may be partially accounted for, but now lvgl seems to be calling `m_free` and `m_realloc` in micropython incorrectly. I'll open this as a draft for now and keep investigating.
Please let me know if the linux build is way behind the mac/other builds and needs a lot of work - I'm not super familiar with these build systems and so if that's the case I might have to give up and leave it to the professionals :sweat_smile:
<details>
<summary>Here's the error in the build</summary>
```
CC ../../micropython/../lv_binding_micropython_tulip/lvgl/src/stdlib/builtin/lv_string_builtin.c …
```
> Fix linux build

- tulip/shared/editor.c
Add a newline back to lines that start with `\0` in them. we no longer store the `\n` in these lines, so the saving function has to add them back in
> fix for editor bug #105

- tulip/linux/build.sh
- tulip/shared/py/tulip.py
This change adds the usage of the XDG Base Directory Specification when referencing `tulip.root_dir()` from Tulip Desktop. This includes updating the Linux build script to use `~/.local/share` instead of `~/Documents` when referencing the desktop version of the root directory.
XDG Base Directory Specification
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
**Testing**
I have tested this change in a Fedora 38 environment, and the output of `tulip.root_dir()` shows the new root directory in `~/.local/share/tulipcc` as expected.
I also built this from source and flashed to my Tulip CC device, and did not find any problems with functionality.  The output of `tulip.root_dir()` there was `/`.
**macOS**
I have not tested this for macOS. However, I noticed that …
> use XDG base directory spec for desktop builds if supported

- docs/tulip_api.md
- tulip/esp32s3/mpconfigport.h
- tulip/shared/display.c
- tulip/shared/midi.c
- tulip/shared/midi.h
- tulip/shared/py/midi.py
- ignore 1 byte midi messages in `midi.py` (for now!)
- increase scheduler depth for fast midi scheduling
- increate `midi.c` queue length for fast midi scheduling
- stop looking for multiple midi messages in a single message -- we don't get those
- turn on tfb logging by default too
> fixes for #318

- docs/getting_started.md
- docs/tulip_api.md
- tulip/esp32s3/main.c
- tulip/esp32s3/uart.c
- tulip/shared/display.c
- tulip/shared/display.h
- tulip/shared/midi.c
- tulip/shared/midi.h
- tulip/shared/modtulip.c
- tulip/shared/py/midi.py
- starting in on midi parser (and also side work on mpremote for it)
- fixed midi parser, and allowing midi.py to do all notes off
> Better midi parser, handles running status. Also support for all notes off

- docs/getting_started.md
- tulip/shared/py/learn_midi_codes.py
If we're going to have midi.oy/juno6.py rely on a json file of midi CCs, we should ship that utility in tulip and manage it here. 
this pulls in dan's `learn_midi_codes.py` from TW and keeps it in the repo. it updates the docs too
> adding learn midi codes directly

- docs/tulip_desktop.md
From a discussion on Discord, it is possible that Tulip Desktop doesn't select a reasonable audio device on startup on Mac OS X and might give no output. The solution is straightforward, but this just makes it more visible in the documentation.
> Add tulip desktop audio device information on Mac OS X to docs

- docs/music.md
- docs/tulip_api.md
- tulip/shared/py/midi.py
- tulip/shared/py/voices.py
This adds a couple of cleanups to the music.md tutorial, with associated code changes.
`midi.config.get_synth()` replaces direct access of `midi.config.synth_per_channel` which was seemingly endorsing direct access of internal data.
`midi.config.add_synth()` gains defaults for all args, and polyphony becomes `num_voices` for consistency with lower levels.
Use of `synth.program_change()` is replaced by `patch_number=X` in the `Synth` constructor.
Python style guide spaces around args.
> midi.py, music.md, ..: Add midi.config.get_synth(), rename polyphony

- tulip/shared/memorypcm.c
This code includes copy-pasta from amy/src/pcm.c.  The bug fix there needs to be (re?)propagated here.
> memorypcm.c: Note-off non-retrigger fix, as for amy/src/pcm.c.

- tulip/esp32s3/gt911_touchscreen.c
update gt911_touchscreen.c to set last_touch_x/y to -1 for all non-down pointers (currently hardcoded to 3)
> pointer fix for gt911_touchscreen.c

- tulip/shared/py/midi.py
Fixes a problem with prematurely terminating a note on pedal-up (release of piano sustain).   Previously, the sequence [pedal down, play & release notes (they sustain), play one of the sounding notes again, hold it down but release the pedal] would execute a note-off for the note that was being held down, because its note-off from the release of the first chord was still pending.  
With this fix, note-on ensures the note in question is not in the list of deferred note-offs, so it is not prematurely terminated.
Thanks to matt-har-vey for identifying the problem and providing the fix!
> midi.py: Fix to remove repeated note from sustained_notes

- tulip/shared/py/midi.py
Thanks to Douglas Repetto for this suggestion.
> midi.py: config.add_synth() returns the new Synth object.

- tulip/shared/py/midi.py
The new dpwe piano wants 25 oscs per voice, and this went badly unless I fully release all the default Synths (and reset the voices system) before attempting `midi.config.add_synth(channel=1, synth=Synth(patch_number=256, num_voices=4))`.  So this command releases any Synths known to midi.config, then calls `Synth.reset()`, which in turn calls `amy.resetI()`.
> midi.py: Add `midi.config.reset()` to release & reset all synths/voices.

- tulip/macos/main.c
- tulip/shared/desktop/unix_mphal.c
This prevents bash from getting messed up on exit. You can also quit TD with control-D now.
> macos desktop control-D quits and restores termios

- tulip/shared/py/_boot.py
- tulip/shared/py/amyboard.py
Works with the one working amyboard prototype.
> amyboard: start_amy in _boot, fix cv_out.

- docs/tulip_api.md
- lv_binding_micropython_tulip/lv_conf.h
- lv_binding_micropython_tulip/lvgl/src/font/lv_font.h
- tulip/shared/display.c
- tulip/shared/lvgl_u8g2.c
- tulip/shared/py/amyboard.py
- tulip/shared/py/voices.py
- tulip/shared/py/worldui.py
- tulip/shared/u8g2_fonts.c
This fixes #203 (finally!)
This lets you use Tulip bitmap fonts in LVGL. We've updated the API docs. See `voices.py` to see how we use it.
> Allow use of un-aliased Tulip fonts in LVGL

- tulip/shared/py/drums.py
AMY is currently built with pcm_tiny.h, which means the PCM presets are only available up to preset=10.  Previously, the drums.py app was trying to use preset=25 for the kick drum, which resulted in a heavily down pitched maraca, which sounded bad.  Here, we change the default voices for the drums.py app to be ones that are available even in "tiny" AMY.
We still have the problem that many of the alternate voices offered by the pulldown in drums.py are not going to work as expected with tiny AMY.  We built drums.py expecting AMY to be compiled with pcm_small.h, but then we ran into AMY size issues for, e.g., RP2040 targets under Arduino, so we cut it back.  Ideally, we'd build AMY with pcm_small when building for a Tulip target.
> shared/py/drums.py: Make default Kick be the one available in AMY 

- tulip/shared/amy_connector.c
bringing current tulip main in sync with pinned Amy.
> shared/amy_connector.c: Remove stray reference to features.dualcore.
